sets aria-label attribute for Path and Coordinates
d3plus/d3plus-geomap pull request #19
Opened 2018-06-25 13:41 UTC by rbaheti

### Description

- Sets aria-label attribute for Path using formula: ${drawLabel}, ${colorScale value}.
- Sets aria-label attribute for Coordinate using formula: ${drawLabel}, ${radius value}.
closes #18

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have documented all new methods.
- [ ] I have written tests for all new methods/functionality.
- [ ] I have written examples for all new methods/functionality.

2018-06-25 19:37 UTC, davelandry requested changes

2018-06-25 19:37 UTC, davelandry commented on src/Geomap.js
> +        ariaLabel: (d, i) => `${this._drawLabel(d, i)}, ${this._colorScale(d, i)}.`,
This needs a catch, similar to the one in d3plus-network regarding size, if the `colorScale` is not defined (only show the label in this case).

2018-06-27 17:22 UTC, davelandry requested changes

2018-06-27 17:22 UTC, davelandry commented on src/Geomap.js
> +          return `${this._drawLabel(d, i)}, ${validColorScale}.`;
remove `", "` from the return statement, as it is being added by the validColorScale.

for example, if a shape named "Alpha" does not have a validColorScale, the label is rendered as `"Alpha, ."`

2018-06-27 18:39 UTC, davelandry approved these changes

2018-06-27 18:39 UTC, merged

2022-07-17 20:31 UTC, yemoku commented
Hello,

Is there a complete sample/example for this, as in providing a caption for each state/shape on the map?

Thanks

2022-07-18 14:27 UTC, davelandry commented
@yemoku this code overrides the aria-label on the `<path>` elements created by a map:

```js
.config({
  shapeConfig: {
    Path: {
      ariaLabel: (d, i) => "my custom label"
    }
  }
})
```

2022-07-18 15:22 UTC, yemoku commented
Thanks for responding. tried that but no joy. My full code: to even put the same label in all the shapes/paths

        var chart = new d3plus.Geomap()
            .topojson(JSON.parse(w.data.map))
            .data(data)
            .legend(false)
            .ocean('transparent')
            .tiles(false)
            .zoom(false)
            .config({
                shapeConfig: {
                    Path: {
                        ariaLabel: (d, i) => "my"
                    }
                }
            })
            .select(cbody).render();

Tried with both d3plus-geomap.full.min.js and d3plus-geomap.full.js from the latest version link

2022-07-18 22:36 UTC, yemoku commented
A small sample for your perusal if you have the time
[FoodCosts.json 20220718 2332.zip](https://github.com/d3plus/d3plus-geomap/files/9136095/FoodCosts.json.20220718.2332.zip)

Thanks

2022-07-19 15:27 UTC, davelandry commented
@yemoku looking at your sample code, I can see that the `ariaLabel` attribute is working correctly (all `<path>` elements are getting their `aria-label` attribute set). The `aria-label` attribute is generally used for screen readers and assistive technologies to make the visualizations more accessible.

<img width="1385" alt="Screen Shot 2022-07-19 at 11 20 37 AM" src="https://user-images.githubusercontent.com/1847581/179787392-a44f659e-f5b0-4270-aa4b-9796d3bd6f20.png">

My hunch is that you are misunderstanding the function of `ariaLabel`, and are looking for actual _visible_ labels that appear for the shapes? If so, then you are missing a config method that links the `data` Array IDs with the unique IDs in your `topojson` data. In your `topojson` data, it looks like you are trying to map States, and those unique State names are nested inside of the `properties` Object of each shape. Add these 3 config methods to link your data to the topojson, color the map by number of projects, and show the number in the tooltips:

```js
.topojsonId(d => d.properties.State)
.colorScale("Projects")
.tooltipConfig({
    tbody: [
        [d => `# of Projects: ${d.Projects}`]
    ]
})
```

2022-07-19 21:07 UTC, yemoku commented
Yes, you are correct about my confusion on aria as opposed to visible labels. 

So the config changes you suggested work for a tooltip. Has there even a config to place actual labels/text on each shape (state in this example) in order to provide the (state0 names?

Thanks

2022-07-19 21:30 UTC, davelandry commented
There is currently no default/shortcut for Geomap labels, but I would use the [`largestRect`](https://github.com/d3plus/d3plus-shape#largestRect) function in conjunction with the `labelBounds` method, which allows you to specify the bounding box of a shape's label:

```js
.shapeConfig({
    label: d => d.id,
    labelBounds: (d, i, s) => {

        const poly = d3plus.largestRect(s.points);

        return poly ? {
            x: poly.cx - poly.width / 2,
            y: poly.cy - poly.height / 2,
            width: poly.width,
            height: poly.height
        } : nulle;

    }
})
```

2022-07-19 21:32 UTC, davelandry commented
https://github.com/d3plus/d3plus/issues/754

2022-07-19 22:15 UTC, yemoku commented
Thanks immensely for this. Will give it a try

 

From: Dave Landry ***@***.***> 
Sent: 19 July 2022 22:31
To: d3plus/d3plus-geomap ***@***.***>
Cc: yemoku ***@***.***>; Mention ***@***.***>
Subject: Re: [d3plus/d3plus-geomap] sets aria-label attribute for Path and Coordinates (#19)

 

There is currently no default/shortcut for Geomap labels, but I would use the  <https://github.com/d3plus/d3plus-shape#largestRect> largestRect function in conjunction with the labelBounds method, which allows you to specify the bounding box of a shape's label:

.shapeConfig({
    label: d => d.id,
    labelBounds: (d, i, s) => {
 
        const poly = d3plus.largestRect(s.points);
 
        return poly ? {
            x: poly.cx - poly.width / 2,
            y: poly.cy - poly.height / 2,
            width: poly.width,
            height: poly.height
        } : nulle;
 
    }
})

—
Reply to this email directly, view it on GitHub <https://github.com/d3plus/d3plus-geomap/pull/19#issuecomment-1189570618> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ACV7FPK5ODCM46ZS53HKQMTVU4NB3ANCNFSM4FGYWGGA> .
You are receiving this because you were mentioned.Message ID: ***@***.***>