More examples
d3plus/d3plus-geomap pull request #27
Opened 2019-05-06 17:22 UTC by rbaheti

### Description

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have documented all new methods.
- [ ] I have written tests for all new methods/functionality.
- [ ] I have written examples for all new methods/functionality.

### Checklist of new examples

- [ ] Geomap Point size
- [ ] Geomap zoom, tiles and ocean configuration
- [ ] Geomap fitFilter example

2019-05-10 16:22 UTC, davelandry requested changes

2019-05-10 16:22 UTC, davelandry commented on example/coordinate-point-size.md
> +# Coordinate Point Size on a Map
Changing Coordinate Point Sizes

2019-05-10 16:22 UTC, davelandry commented on example/coordinate-point-size.md
> +For a coordinate point [Geomap](https://d3plus.org/docs/#Geomap), you can specify the point size by setting the [pointSize](https://d3plus.org/docs/#Geomap.pointSize) property to an indicator you wan
```md
For a coordinate point [Geomap](https://d3plus.org/docs/#Geomap), you can enable dynamic point sizing by setting the [pointSize](https://d3plus.org/docs/#Geomap.pointSize) property to an accessor that returns the data value you want to use. Additionally, the minimum and maximum values used in the scaling can be overridden using the [pointSizeMin](https://d3plus.org/docs/#Geomap.pointSizeMin) and [pointSizeMax](https://d3plus.org/docs/#Geomap.pointSizeMax) methods:
```

2019-05-10 16:22 UTC, davelandry commented on example/remove-tiles-from-geomap.md
> +[Geomap](https://d3plus.org/docs/#Geomap) tiles can be removed by setting the `tiles` property to false. Similarly, by setting `ocean` property to transparent will hide ocean on the map. To hide the
```md
[Geomap](https://d3plus.org/docs/#Geomap) background tiles can be removed by setting the `tiles` property to `false`. The `ocean` property can then be changed to alter the overall background color, with `"transparent"` being used to remove the background color entirely.
```

2019-05-10 16:22 UTC, davelandry commented on example/remove-tiles-from-geomap.md
> +    zoom: false,
make a different example to show the different zoom behaviors you can disable

2019-05-10 16:22 UTC, davelandry commented on example/remove-tiles-from-geomap.md
> +    tiles: false,
remove trailing comma

2019-05-10 16:22 UTC, davelandry commented on example/show-required-area.md
> +# Show Required Area on Geomap
Change Default Geomap Zooming

2019-05-10 16:22 UTC, davelandry commented on example/show-required-area.md
> +Topojson files sometimes include small geographies that negatively impact how the library determines the default zoom level (for example, a small island or territory far off the coast that is barely
add link for `fitFilter`

2019-05-10 16:23 UTC, davelandry requested changes

2019-05-10 16:23 UTC, davelandry commented on package.json
> +    "d3plus-shape": "^0.14.11",
why is this being committed to this PR?

2019-05-10 16:23 UTC, davelandry commented on src/Geomap.js
> +      ariaLabel: (d, i) => `${this._drawLabel(d, i)}, ${this._pointSize(d, i)}`,
why is this being committed to this PR?

2019-05-11 02:55 UTC, rbaheti commented on package.json
> +    "d3plus-shape": "^0.14.11",
Sorry, reverted it.

2019-05-11 02:55 UTC, rbaheti commented on src/Geomap.js
> +      ariaLabel: (d, i) => `${this._drawLabel(d, i)}, ${this._pointSize(d, i)}`,
Sorry, reverted it.

2019-05-14 13:22 UTC, davelandry requested changes

2019-05-14 13:22 UTC, davelandry commented on example/disable-geomap-zoom-controls.md
> +# Disable Geomap Zoom Controls
Disable Geomap Zooming

2019-05-14 13:22 UTC, davelandry commented on example/disable-geomap-zoom-controls.md
> +For a [Geomap](https://d3plus.org/docs/#Geomap), zoom controls are enabled by default. To disable them, set the [zoom](https://d3plus.org/docs/#Viz.zoom) property to `false`.
```md
For a [Geomap](https://d3plus.org/docs/#Geomap), zooming is enabled by default. To disable them entirely, set the [zoom](https://d3plus.org/docs/#Viz.zoom) property to `false`.
```

2019-05-14 13:22 UTC, davelandry commented on example/remove-tiles-from-geomap.md
> +    ocean: "transparent"
looks like you removed `tiles` instead of removing `zoom`

2019-05-17 14:32 UTC, davelandry requested changes
There are downgrading changes in `package.json`, `package-lock.json`, and `src/Geomap.js`. Try to resolve these by pulling/merging from master into this branch (not the other way around). If that doesn't work, please close this PR and make a new one based on the current master branch.

2019-05-21 16:23 UTC, closed without merging